site :opscode

cookbook 'apt', '~> 1.10'
cookbook 'rvm', git: 'git://github.com/fnichol/chef-rvm.git'
cookbook 'libidn', git: 'git://github.com/froschi/chef-cookbook-libidn.git'
cookbook 'libssl', git: 'git://github.com/froschi/chef-cookbook-libssl.git'

# see https://github.com/opscode-cookbooks/runit/pull/23
cookbook 'runit', git: 'git://github.com/noazark/runit.git', ref: '31a6cf67fa'
cookbook 'wget', git: 'git://github.com/froschi/chef-cookbook-wget.git'
cookbook 'nexus', git: 'git://github.com/RiotGames/nexus-cookbook.git'
cookbook 'maven', git: 'git://github.com/opscode-cookbooks/maven.git'
cookbook 'chef-jenkins-job-builder', git: 'git://github.com/needle-cookbooks/chef-jenkins-job-builder.git'
cookbook 'git',git: 'git://github.com/opscode-cookbooks/git.git'
cookbook 'jenkins-jobs', git: 'git://github.com/jaypipes/cookbook-jenkins-jobs.git'
